CREATE USER IF NOT EXISTS "SA" PASSWORD '' ADMIN;
CREATE SEQUENCE "PUBLIC"."BREEDS_SEQ" START WITH 1 RESTART WITH 151 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."IMAGES_SEQ" START WITH 1 RESTART WITH 17951 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."sub-breed_seq" START WITH 1 RESTART WITH 151 INCREMENT BY 50;
CREATE MEMORY TABLE "PUBLIC"."BREED_SUB_BREED"(

    "BREED_ID" BIGINT NOT NULL,

    "SUB_BREED_ID" BIGINT NOT NULL

);
ALTER TABLE "PUBLIC"."BREED_SUB_BREED" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("BREED_ID", "SUB_BREED_ID");
-- 82 +/- SELECT COUNT(*) FROM PUBLIC.BREED_SUB_BREED;
CREATE MEMORY TABLE "PUBLIC"."BREEDS"(

    "ID" BIGINT NOT NULL,

    "NAME" CHARACTER VARYING(255) NOT NULL

);
ALTER TABLE "PUBLIC"."BREEDS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_75" PRIMARY KEY("ID");
-- 99 +/- SELECT COUNT(*) FROM PUBLIC.BREEDS;
CREATE MEMORY TABLE "PUBLIC"."IMAGES"(

    "BREED_ID" BIGINT SELECTIVITY 1,

    "ID" BIGINT SELECTIVITY 100 NOT NULL,

    "sub_breed_id" BIGINT SELECTIVITY 1,

    "IMAGE_LINK" CHARACTER VARYING(255) SELECTIVITY 100 NOT NULL

);
ALTER TABLE "PUBLIC"."IMAGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");
-- 17871 +/- SELECT COUNT(*) FROM PUBLIC.IMAGES;
CREATE MEMORY TABLE "PUBLIC"."sub-breed"(

    "ID" BIGINT NOT NULL,

    "NAME" CHARACTER VARYING(255) NOT NULL

);
ALTER TABLE "PUBLIC"."sub-breed" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A7" PRIMARY KEY("ID");
-- 63 +/- SELECT COUNT(*) FROM PUBLIC."sub-breed";
ALTER TABLE "PUBLIC"."sub-breed" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" UNIQUE("NAME");
ALTER TABLE "PUBLIC"."BREEDS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" UNIQUE("NAME");
ALTER TABLE "PUBLIC"."BREED_SUB_BREED" ADD CONSTRAINT "PUBLIC"."FK4QCBUTS6IJ4X4RCI5R4MSVD7B" FOREIGN KEY("SUB_BREED_ID") REFERENCES "PUBLIC"."sub-breed"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."IMAGES" ADD CONSTRAINT "PUBLIC"."FKM42I8NOIUSF9MU0917FYLPWHC" FOREIGN KEY("sub_breed_id") REFERENCES "PUBLIC"."sub-breed"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."IMAGES" ADD CONSTRAINT "PUBLIC"."FKPI2F1INIFX7KTWR719SYEY3P1" FOREIGN KEY("BREED_ID") REFERENCES "PUBLIC"."BREEDS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BREED_SUB_BREED" ADD CONSTRAINT "PUBLIC"."FK3X0KPLQFXOWU0DDR4Q6N8X2G8" FOREIGN KEY("BREED_ID") REFERENCES "PUBLIC"."BREEDS"("ID") NOCHECK;
